plugins {
	id 'java-library'
	id 'maven-publish'
	id 'net.neoforged.moddev' version '2.0.141'
}

base {
	archivesName = "${mod_id}-api-${minecraft_version}"
}

java {
	toolchain.languageVersion = JavaLanguageVersion.of(java_version)
	withSourcesJar()
}

neoForge {
	neoFormVersion = neo_form_version
}

dependencies {
	compileOnly 'net.fabricmc:sponge-mixin:0.17.3+mixin.0.8.7'
	if (providers.gradleProperty('localMcgltfApi').isPresent()) {
		compileOnly files(providers.gradleProperty('localMcgltfApi').get())
	} else {
		compileOnly "com.modularmods.mcgltf:mcgltf-api:${mcgltf_version}"
	}
}

tasks.withType(Jar).configureEach {
	from(rootProject.file('LICENSE')) {
		rename { "${it}_${mod_name}" }
	}
}

publishing {
	publications {
		register('mavenJava', MavenPublication) {
			artifactId base.archivesName.get()
			from components.java
		}
	}
}
